spring:
  data:
    mongodb:
      uri: mongodb+srv://nirujs01:ixgaSQCsPSR8mc38@cluster0.763mtfq.mongodb.net/EmployeeDetails



      thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

